#!/usr/bin/env ruby
# encoding: utf-8

require 'date'
require 'slack-notifier'

require_relative 'slack_common'

team_config = get_slack_team_config(ARGV[1])
channel     = get_slack_channel(ARGV[1], ARGV[0])
slack_url   = get_slack_url(ARGV[1], ARGV[2])

birthdays = Hash[(team_config['birthdays'] || {}).map { |u, b| [u, Date.parse(b)] }]

today          = Date.today
tomorrow       = today + 1
tomorrowmorrow = today + 2

birthdays_today = Hash[birthdays.find_all do |user, birthday|
  if today.saturday? or today.sunday?
    false
  else
    birthday.month == today.month and birthday.day == today.day
  end
end]
birthdays_coming = Hash[birthdays.find_all do |user, birthday|
  unless today.friday?
    false
  else
    (birthday.month == tomorrow.month && birthday.day == tomorrow.day) ||
    (birthday.month == tomorrowmorrow.month and birthday.day == tomorrowmorrow.day)
  end
end]

notifier = Slack::Notifier.new slack_url, channel: channel, username: 'BirthdayBot', icon_emoji: ':birthday:'

if birthdays_today.empty? and birthdays_coming.empty?
  puts "Ingen att gratulera."
elsif not birthdays_today.empty? and not birthdays_coming.empty?
  puts "Gratulerar #{birthdays_today.map { |u, b| u }.join(', ')} samt #{birthdays_coming.map { |u, b| u }.join(', ')}."
  notifier.ping "Vi gratulerar #{birthdays_today.map { |u, b| "*#{u}*" }.join(' och ')} som *fyller år idag*, samt #{birthdays_coming.map { |u, b| "*#{u}*" }.join(' och ')} som *fyller år i helgen!*"
elsif not birthdays_today.empty?
  puts "Gratulerar #{birthdays_today.map { |u, b| u }.join(', ')}."
  notifier.ping "Idag gratulerar vi #{birthdays_today.map { |u, b| "*#{u}*" }.join(' och ')} som *fyller år!*"
elsif not birthdays_coming.empty?
  puts "Gratulerar #{birthdays_coming.map { |u, b| u }.join(', ')}."
  notifier.ping "Idag gratulerar vi #{birthdays_coming.map { |u, b| "*#{u}*" }.join(' och ')} som *fyller år i helgen!*"
end
